name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  avro-1_11_3-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./avro-plugin-reproducer-1_11_3
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: maven
      - name: Build with Maven
        run: ./mvnw -X -B clean compile --file pom.xml
  avro-1_12_0-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./avro-plugin-reproducer-1_12_0
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: maven
      - name: Build with Maven
        run: ./mvnw -X -B clean compile --file pom.xml